# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "weekly"
