framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: '%env(DEFAULT_URI)%'

        strict_requirements: true

when@prod:
    framework:
        router:
            strict_requirements: null
