when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        # this hooks into critical paths of the framework (and vendors) to perform
        # automatic instrumentation (there might be some performance penalty)
        # https://docs.sentry.io/platforms/php/guides/symfony/performance/instrumentation/automatic-instrumentation/
        tracing:
            enabled: false

#        If you are using Monolog, you also need this additional configuration to log the errors correctly:
#        https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
#        register_error_listener: false
#        register_error_handler: false

#    monolog:
#        handlers:
#            sentry:
#                type: sentry
#                level: !php/const Monolog\Logger::ERROR
#                hub_id: Sentry\State\HubInterface

#    services:
#        Sentry\Monolog\Handler:
#            arguments:
#                $hub: '@Sentry\State\HubInterface'
#                $level: !php/const Monolog\Logger::ERROR
#                $bubble: false

        options:
            integrations:
                - 'Sentry\Integration\IgnoreErrorsIntegration'

    services:
        Sentry\Integration\IgnoreErrorsIntegration:
            arguments:
                $options:
                    ignore_exceptions:
                        - Symfony\Component\HttpKernel\Exception\NotFoundHttpException

#    Uncomment these lines to register a log message processor that resolves PSR-3 placeholders
#    https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
#    services:
#        Monolog\Processor\PsrLogMessageProcessor:
#            tags: { name: monolog.processor, handler: sentry }
