sudo: false

language: php

php:
  - 7.2
  - 7.1
  - 7.0

before_script:
  - composer self-update

install:
  - composer install

stages:
  - code_style
  - test
  - code_coverage
  - update_check

script: vendor/bin/codecept run --ansi

jobs:
  include:
    - stage: code_style
      script: vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --ansi --allow-risky=yes --diff
    - stage: cove_coverage
      script: vendor/bin/codecept run --coverage --coverage-xml --ansi
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: update_check
      script: composer outdated --direct --strict --ansi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

