sudo: false

language: php

php:
  - 7.2
  - 7.1
  - 7.0

before_script:
  - composer self-update

install:
  - composer install

stages:
  - code_style
  - tests
  - update_check

jobs:
  include:
    - stage: code_style
      script: vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --ansi --allow-risky=yes --diff
    - stage: tests
      script: vendor/bin/codecept run --coverage --coverage-html --ansi
    - stage: update_check
      script: composer outdated --direct --strict --ansi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
