dist: focal

language: php

php:
  - '8.0'

install:
  - composer install

# define script for default stage 'test' separately so it will only be
# run once for every php version specified above
script: composer codeception

# don't fail on deprecation warnings for now as they come from
# dependencies, not from the test code in this repository
env:
  - SYMFONY_DEPRECATIONS_HELPER=max[self]=0

# and specify that 'test' stage should run after 'code quality' checks
stages:
  - "code quality"
  - test

# define additional jobs/stages
jobs:
  include:
    - stage: "code quality"
      script: composer lint-yaml
      name: "lint yaml"
    - script: composer lint-container
      name: "lint container"
    - script: composer lint-twig
      name: "lint twig"
    - script: composer php-cs-fixer
      name: "php-cs-fixer"
    - script: composer phpstan
      name: "phpstan"
    - script: composer phpcs
      name: "phpcs"
    - stage: "tests"
      script: composer codeception-coverage-xml
      name: "codeception"
      env: XDEBUG_MODE=coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "update check"
      script: composer update-check
      env: ALLOW_FAILURE=true
  allow_failures:
    - env: ALLOW_FAILURE=true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
