language: php

php:
  - '7.2'
  - '7.3'

before_script:
  - composer self-update

install:
  - composer install

# define script for default stage 'test' separately so it will only be
# run once for every php version specified above
script: composer codeception

# don't fail on deprecation warnings for now as they come from
# dependencies, not from the test code in this repository
env:
  - SYMFONY_DEPRECATIONS_HELPER=disabled

# and specify that 'test' stage should run after 'code quality' checks
stages:
  - "code quality"
  - test

# define additional jobs/stages
jobs:
  include:
    - stage: "code quality"
      script: composer php-cs-fixer
      name: "php-cs-fixer"
    - script: composer phpstan
      name: "phpstan"
    - script: composer phpcs
      name: "phpcs"
    - stage: "code coverage"
      script: composer codeception-coverage-xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "update check"
      script: composer update-check

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

