services:
    app:
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:80"
        env_file:
            - .env
        environment:
            - APP_ENV=dev
            - APP_DEBUG=true
